doc/index.md

Translate a FAQ in index.md

---

doc/storage.md

Translate the "Storage pool configuration" section

---

doc/profiles.md

Translate profiles.md

---

doc/debugging.md

Move comment of chapter titles in debugging.md

---

doc/index.md

Translated all index.md

---

doc/requirements.md

Translate requirements.md

---

doc/storage.md

Translate the section of Storage volume configuration in storage.md

---

doc/backup.md

Translate backup.md

---

doc/storage.md

Translate the section of feature comparison in storage.md

---

doc/daemon-behavior.md

Translate daemon-behavior.md

---

doc/storage.md

Translate some sections in storage.md

---

doc/database.md

Translate database.md

---

doc/container-environment.md

 Translate container-environment.md

---

doc/configuration.md

Translate configuration.md

---

doc/dev-lxd.md

Translate dev-lxd.md

---

doc/configuration.md

Fix markdown comments for configuration.md

---

doc/container-environment.md

Fix comment-outs of English lists in container-environment.md

---

doc/preseed.md

Translate preseed.md

---

doc/userns-idmap.md

Translate userns-idmap.md

---

doc/storage.md

Translate I/O limit section in storage.md

---

doc/storage.md

Translate btrfs section in storage.md

---

doc/storage.md

Translate LVM section in storage.md

---

doc/image-handling.md

Translate image-handling.md

---

doc/networks.md

Translate networks.md

---

doc/storage.md

Translate ZFS section in storage.md

---

doc/server.md

Translate server.md

---

doc/api-extensions.md

Translate api-extensions.md

---

doc/contributing.md

Translate contributing.md

---

doc/security.md

Update security.md to upstream at 2018-10-04

---

doc/clustering.md

Update clustering.md to upstream at 2018-10-04

---

doc/index.md

Update index.md to upstream at 2018-10-04

---

doc/database.md

Updating database.md to upstream at 2018-10-04

---

doc/api-extensions.md

Update api-extensions to upstream at 2018-10-04

---

doc/server.md

Update server.md to upstream at 2018-10-04

---

doc/storage.md

"security.unmapped" for storage volume configuration

Add a missing key to table in storage.md

---

doc/index.md
doc/requirements.md

* Bump golang requirement to 1.10 or higher
* Update build instruction

Update some docs to upstream at 2018-11-05

---

doc/server.md

空白を除いた変更は以下のリンクでご確認ください。
原文
https://github.com/lxc-jp/lxd-ja/commit/9adfc2559619f400b2a386408eae9ead2bb2b56c?w=1
日本語訳
https://github.com/lxc-jp/lxd-ja/pull/66/files?w=1

Update server.md to upstream at 2019-01-10

---

doc/backup.md
doc/rest-api.md

Update backup.md and rest-api.md to upstream at 2019-03-13

---

doc/containers.md

Update containers.md to upstream at 2019-03-13

---

doc/api-extensions.md

Update api-extensions.md to upstream at 2019-03-13

---

doc/debugging.md

Update debugging.md to upstream at 2019-03-13

---

doc/storage.md

Update storage.md to upstream at 2019-03-13

---

doc/storage.md

Tweak markdown format in storage.md

---

doc/index.md

Update index.md to upstream at 2019-05-17

---

doc/storage.md

Update storage.md to upstream at 2019-05-17

---

doc/server.md

Update server.md to upstream at 2019-05-17

---

doc/containers.md

Update containers.md to upstream at 2019-05-17

---

doc/containers.md

Fix comment section

---

doc/api-extensions.md

Update api-extensions.md to upstream at 2019-05-17

---

doc/environment.md
doc/rest-api.md
doc/server.md

Update {environment,rest-api,server}.md to upstream at 2019-07-11

---

doc/security.md

Update security.md to upstream at 2019-07-11

---

doc/storage.md

Update storage.md to upstream at 2019-07-11

---

doc/index.md

Update index.md to upstream at 2019-07-11

---

doc/containers.md

Update containers.md to upstream at 2019-07-11

---

doc/api-extensions.md

Update api-extensions.md to upstream at 2019-07-11

---

doc/syscall-interception.md
mkdocs.yml

Add and Translate syscall-interception.md

---

doc/containers.md

すみません、原文のコメントアウトが出来てなかった箇所の修正です。

Fix comment out

---

doc/contributing.md

Update contributing.md to upstream at 2019-11-18

---

doc/index.md

Update index.md to upstream at 2019-11-18

---

doc/api-extensions.md

also make some changes to make the translation consistent.

Update api-extensions.md to upstream at 2020-01-10

---

doc/metadata.yaml
doc/virtual-machines.md

Add virtual-machines.md as of upstream at 2020-01-10

---

mkdocs.yml

Update menu to match official English documents

---

mkdocs.yml

Translate "Getting started"

---

doc/rest-api.md

Update rest-api.md to upstream at 2020-01-10

---

doc/profiles.md

Update profiles.md to upstream at 2020-01-10

---

doc/networks.md

Update networks.md to upstream at 2020-01-10

---

doc/index.md

Update index.md to upstream at 2020-01-10

---

doc/image-handling.md

Update image-handling.md to upstream at 2020-01-10

---

doc/instances.md
doc/metadata.yaml

instances.md のほとんどの部分は containers.md 内の container を instance に置換したものになっていますが、一部追加部分もありました。

Add instances.md as of upstream at 2020-01-10

---

doc/dev-lxd.md

Update dev-lxd.md to upstream at 2020-01-10

---

doc/environment.md

Update environment.md to upstream at 2020-01-10

---

doc/storage.md

Update storage to upstream at 2020-01-31

---

doc/security.md

Update security to upstream at 2020-01-31

---

doc/rest-api.md

Update rest-api to upstream at 2020-01-31

---

doc/projects.md

Update projects to upstream at 2020-01-31

---

doc/production-setup.md

Update production-setup to upstream at 2020-01-31

---

doc/networks.md

Update networks to upstream at 2020-01-31

---

doc/migration.md

Update migrations to upstream at 2020-01-31

---

doc/instances.md

Update instances to upstream at 2020-01-31

---

doc/image-handling.md

Update image-handling to upstream at 2020-01-31

---

doc/faq.md

Update faq to upstream at 2020-01-31

---

doc/dev-lxd.md

Update dev-lxd to upstream at 2020-01-31

---

doc/debugging.md

Update debugging to upstream at 2020-01-31

---

doc/database.md

Update database to upstream at 2020-01-31

---

doc/daemon-behavior.md

Update daemon-behavior to upstream at 2020-01-31

---

doc/configuration.md

Update configurations to upstream at 2020-01-31

---

doc/clustering.md

Update clustering to upstream at 2020-01-31

---

doc/cloud-init.md

Update cloud-init.md to upstream at 2020-01-31

---

doc/backup.md

Update backup.md to upstream at 2020-01-31

---

doc/api-extensions.md

Update api-extensions.md to upstream at 2020-01-31

---

doc/index.md

Update index to upstream at 2020-01-31

---

doc/instances.md

Update instances to upstream at 2020-02-13

---

doc/clustering.md

Update clustering to upstream at 2020-02-13

---

doc/api-extensions.md

Update api-extensions to upstream at 2020-02-13

---

doc/api-extensions.md
doc/container-environment.md
doc/instances.md
doc/requirements.md

We need line feeds for correct itemization

---

doc/api-extensions.md
doc/instances.md
doc/rest-api.md

Update translations to upstream at 2020-05-09 (closes #160)

---

doc/api-extensions.md
doc/instances.md
doc/rest-api.md
doc/storage.md

Update translations to upstream at 2020-07-02 (closes #164)

---

doc/api-extensions.md
doc/environment.md
doc/image-handling.md
doc/instances.md
doc/projects.md

Update translations to upstream at 2021-01-09 (Closes #179)

---

doc/api-extensions.md
doc/index.md
doc/instances.md
doc/networks.md
doc/rest-api.md
doc/storage.md

Update translations to upstream at 2021-02-05 (Closes #181)

---

mkdocs.yml

Update side menu (mkdocs.yaml) for network ACL doc

---

doc/api-extensions.md
doc/backup.md
doc/cloud-init.md
doc/clustering.md
doc/instances.md
doc/metadata.yaml
doc/rest-api.yaml

Update Update translations of LXD 4.17 (Closes #195)

---

doc/backup.md
mkdocs.yml

Test adding anchor using attr_list markdown extension

---

doc/backup.md

Test adding anchor take #3

---

doc/backup.md

Add anchor take #4

---

mkdocs.yml

Add external resources to mkdocs.yml

---

mkdocs.yml

This reverts commit 47cd3212e457c539a3b9efdf8caa3eb25442dc46.

Revert "Add external resources to mkdocs.yml"

---

doc/configuration.md
doc/external_resources.md
doc/getting_started.md
doc/images.md
doc/index.md
doc/internals.md
doc/operation.md
doc/restapi_landing.md

Comment out toctrees
